### ISSUE TITLE
Thank you sir for last replay

### ISSUE THREAD

**Issue by coaxtron** [IramML/UberClone#2]
sir now cancle buttom in not working properly sir can you give complet clone plzz sir it will help for my project .

**Comment by IramML** [comment]
Ok, i'm going to complete this clone

**Comment by coaxtron** [comment]
Thank you sir
Love you sir

Sir
   When will complete this.i am waiting sir.
Once again thank you sir.

**Comment by coaxtron** [comment]
Sir when will you complete .
I am waiting sir.

**Comment by coaxtron** [comment]
Thank you sir .
I am waiting for it.
Love u sir

**Comment by coaxtron** [comment]
Sir i am waiting sir plzz complete

**Comment by IramML** [comment]
@coaxtron  I'm sorry, I was a little busy. I am paying attention to this again. This issue was resolved in [this commit](https://github.com/IramML/UberClone/commit/8049e4f81bef73d23c36c055ac2afc8923abe14c). I will try to complete this in the aforementioned time.
