### ISSUE TITLE
Rider app

### ISSUE THREAD

**Issue by coaxtron** [IramML/UberClone#3]
sir
  Now rider app is working properly it's crash when open.

**Comment by IramML** [comment]
@coaxtron crash when open? Can you give me more details?. When open works well for me.

**Comment by IramML** [comment]
@coaxtron I hope that in this new commit works well. But if it does not work please, show me what the logcat says when crashing.

**Comment by coaxtron** [comment]
Thank you sir
Sir when will you complete this project.
I am waiting sir

**Comment by IramML** [comment]
@coaxtron this week i will complete this clone.
