### ISSUE TITLE
REQUEST PICKUP

### ISSUE THREAD

**Issue by coaxtron** [IramML/UberClone#4]
sir 
  Request pickup not working in rider side sir
thank you sir

**Comment by IramML** [comment]
@coaxtron Are you using the login with google?

**Comment by coaxtron** [comment]
yes sir

**Comment by coaxtron** [comment]
sorry sir with google login it,s crash

**Comment by IramML** [comment]
@coaxtron I already solved it, later I make a commit with the full clone, although I plan to add some functions later.

**Comment by coaxtron** [comment]
Thanks you sir
Sir can you give WhatsApp no.
Or any contact plzz sir

**Comment by IramML** [comment]
@coaxtron +5218714872010

**Comment by coaxtron** [comment]
Sir when you will complete this clone

**Comment by coaxtron** [comment]
Sir when you will complete the clone
I am waiting sir

**Comment by IramML** [comment]
@coaxtron for me it is already complete but what function do you want to add to the clone?
