### ISSUE TITLE
A very brief setup guide

### ISSUE THREAD

**Issue by winsagetech** [IramML/UberClone#5]
This is just a suggestion that a very brief setup guide including Firebase, Google APIs or any other services etc will be very helpful. 
If not setup, at least a list of prerequisites will also help people a lot.

**Comment by git1998** [comment]
Can we get brief setup guide for this project?.Actually we wanna work on your project but those prerequesties are not enough for development.So please give complete setup.It will be very helpful to us...
Thank you

**Comment by IramML** [comment]
Ok, I'm going to work on it

**Comment by IramML** [comment]
I already put this on [this new commit](https://github.com/IramML/UberClone/commit/01474a56dd8cd76169a2ed881eb54c86fe4420bc)
