### ISSUE TITLE
Again about brief setup

### ISSUE THREAD

**Issue by git1998** [IramML/UberClone#6]
Can we get brief setup guide for this project?.Actually we wanna work on your project but those prerequesties are not enough for development.So please give complete setup.It will be very helpful to us...
Thank you

**Comment by IramML** [comment]
Sure, I'm going to write that

**Comment by IramML** [comment]
I already put this on [this new commit](https://github.com/IramML/UberClone/commit/01474a56dd8cd76169a2ed881eb54c86fe4420bc)
